# Generated by Django 4.1.7 on 2023-03-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField()),
                ('member_name', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateField()),
                ('requested', models.CharField(max_length=100)),
                ('embossed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('received', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('collected', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csdapp.branch')),
            ],
        ),
    ]
